FROM rubinlab/mysql

# docker build -t srcc/epad:mysql -f Dockerfile.mysql .

# Make a symbolic link from DicomProxy to mysql before start
#RUN ln -s /root/DicomProxy/mysql /var/lib/mysql
#RUN mv /home/install.sh /docker-entrypoint-initdb.d/

ADD entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
