apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: exist
  name: exist
spec:
  ports:
  - name: "8899"
    port: 8899
    targetPort: 8899
  selector:
    io.kompose.service: exist
status:
  loadBalancer: {}
